//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PizzaEntities3 : DbContext
    {
        public PizzaEntities3()
            : base("name=PizzaEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kampanyalar> Kampanyalars { get; set; }
        public virtual DbSet<MusteriBilgi> MusteriBilgis { get; set; }
        public virtual DbSet<Siparisler> Siparislers { get; set; }
    }
}
