//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparisler
    {
        public int SiparisNo { get; set; }
        public string AdSoyad { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string Adres { get; set; }
        public string PizzaBoyu { get; set; }
        public string Icecek { get; set; }
        public string Icındekiler { get; set; }
    }
}
